import type { Metadata } from "next";
import "./globals.css";
import { AppRoot } from "@portifolio/components/AppRoot";
import { ApplicationLayout } from "@portifolio/components/ApplicationLayout";
import { NavigationMenu } from "./navigation-menu";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(props: Readonly<{ children: React.ReactNode; }>) {
    return (
        <AppRoot>
            <ApplicationLayout
                side={<NavigationMenu />}
                main={props.children}
            />
        </AppRoot>
    );
}
